name: Latest videos youtube post workflow
on:
#   schedule:
#     - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCbgTopUOJCunW_6CZjgxQhwµ        
          comment_tag_name: YOUTUBE-CARDS
          # youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          output_type: html
